### ISSUE TITLE
feat: 동영상 저장 뷰 서버 연결

### ISSUE THREAD

**Issue by yunyezl** [depromeet/everyBody-iOS#104]
## 💡 issue
동영상 저장 뷰 서버 연결

## 📝 todo
- [x] 이미지 Key 값 보내서 영상 다운로드
- [ ] 영상 다운로드 하는 동안 팝업 로티 -> #107 에서 처리
- [x] 비디오 다운로드 받은 후 사용자 갤러리에 저장 처리
