### ISSUE TITLE
bug: 파노라마 뷰 여러가지 버그 픽스 및 리팩토링

### ISSUE THREAD

**Issue by anyukyung** [depromeet/everyBody-iOS#114]
## 📝 todo
- [x] 파노라마 바텀 셀 selectItem시 탑 셀 바뀌지않음
- [ ] 파노라마 초기세팅 마지막 셀로 변경
- [x] 섬광 현상 -> get해오는 거 viewWillAppear말고 사진찍고 돌아왔을 때로 변경
- [x] 스크롤 되는 도중 다른 바디파트 누르면 터짐
- [x] 삭제하고 다른 바디파트 누르면 터짐...

💣 🧨
