### ISSUE TITLE
feat: 버전 업데이트를 위한 기타 수정 사항

### ISSUE THREAD

**Issue by yunyezl** [depromeet/everyBody-iOS#170]
## 💡 issue
Realm 마이그레이션 이후 서버가 종료 될 예정이라, 서버 데이터를 사용하던 부분을 임시로 수정합니다.
피드백은 일단 유지합니다.

## 📝 todo
- [x] 프로필 뷰 화면 이동 제한
- [x] 강제 업데이트 Siren 프레임워크 사용
- [x] 피드백 보낼 때, 버전 정보와 모델 정보 같이 보내기
