### ISSUE TITLE
feat: 앨범 UI 개선

### ISSUE THREAD

**Issue by anyukyung** [depromeet/everyBody-iOS#197]
## 💡 issue
이슈에 대한 내용을 설명해주세요.
앨범 UI 개선

## 📝 todo
- [ ] 앨범 디폴트 레이아웃 그리드로 변경
- [ ] 사진 선택시 파노라마로 변경
- [ ] 삭제 플로우 변경
