### ISSUE TITLE
feat: 완료 버튼 선택 시 image와 label을 합치는 작업

### ISSUE THREAD

**Issue by yunyezl** [depromeet/everyBody-iOS#24]
## 💡 issue
촬영 버튼을 누르는 과정이 아닌 촬영 후 완료 버튼을 눌렀을 때 이미지 merge 작업을 수행합니다.

## 📝 todo
- [ ] UIImageView의 Extension으로 이미지 merge 관련 함수 추가
- [ ] UIImageView, UILabel의 상위 ContainerView 생성 후 Snapshot 하여 image merge
- [ ] 사용자의 갤러리 저장 여부에 따라 분기처리
