### ISSUE TITLE
feat: switch 버튼 상태 저장하기

### ISSUE THREAD

**Issue by yunyezl** [depromeet/everyBody-iOS#84]
## 💡 issue
앱 내에 존재하는 스위치 버튼의 상태값을 저장합니다.

## 📝 todo
- [x] Property Wrapper 이용하여 UserDafault 리팩토링
- [x] 앱에만 저장하기 로직 구현 
- [x] 푸시알림 On/Off 상태 저장 밑 로직 구현
- [x] 카메라 그리드 스위치 버튼 상태 저장
