### ISSUE TITLE
chore: 사용성 개선

### ISSUE THREAD

**Issue by yunyezl** [depromeet/everyBody-iOS#94]
## 💡 issue
자잘한 UI/UX 사용성 관련 작업을 합니다.

## 📝 todo
- [ ] 버튼 시스템 highlighted 작업 (지금 눌렸을 때 반응이 없어서 눌렸나? 안눌렸나? 애매함)
- [x] 폴더 / 앨범 워딩 통일
- [ ] 카메라 촬영 버튼 눌렀을 때 카메라 세션 멈추기
- [x] 네트워크 에러 토스트 띄우기
